//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbEquipment
    {
        public int EquipmentID { get; set; }
        public string EquipmentName { get; set; }
        public string EquipmentDescription { get; set; }
        public string EquipmentSerial { get; set; }
        public string EquipmentLocation { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> EquipmentLastSert { get; set; }
        public Nullable<System.DateTime> EquipmentNextSert { get; set; }
    
        public virtual dbLocation dbLocation { get; set; }
    }
}
