//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbContacts
    {
        public int ContactID { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> Type { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string ImageUrl { get; set; }
        public string Birthday { get; set; }
        public string Phone { get; set; }
        public string Position { get; set; }
        public string Company { get; set; }
    }
}
